baseURL = "https://hjr265.me/"
languageCode = "en-us"
title = "hjr265.me"
enableRobotsTXT = true
disqusShortname = "https-hjr265-me"

[taxonomies]
tag = "tags"

[menu]
[[menu.main]]
name = "Blog"
url = "/blog/"

[[menu.main]]
name = "Projects"
url = "/projects/"

[[menu.main]]
name = "Timeline"
url = "/timeline/"

[markup.highlight]
lineNos = true

[markup.goldmark.renderer]
unsafe = true

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "production"
url = "s3://hjr265.me?region=ap-south-1&endpoint=ap-south-1.linodeobjects.com&s3ForcePathStyle=true"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|woff|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "max-age=7200, must-revalidate, public"
gzip = true
