baseURL = "https://hjr265.me/"
languageCode = "en-us"
title = "hjr265.me"
enableRobotsTXT = true
disqusShortname = "https-hjr265-me"

[params]
github = "hjr265"
goatCounterHost = "goatcounter.hjr265.me"

[params.author]
name = "Mahmud Ridwan"
email = "m@hjr265.me"

[taxonomies]
tag = "tags"

[menu]
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Open Source"
url = "/open-source/"
weight = 3

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 4

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 5

[[menu.main]]
name = "Timeline"
url = "/timeline/"
weight = 6

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 7

[markup.highlight]
lineNos = true

[markup.goldmark.renderer]
unsafe = true

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "production"
url = "s3://hjr265.me?region=ap-south-1&endpoint=ap-south-1.linodeobjects.com&s3ForcePathStyle=true"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|woff|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "max-age=0, no-cache, public"
