baseURL = "https://hjr265.me/"
languageCode = "en-us"
title = "hjr265.me"
enableRobotsTXT = true
disqusShortname = "https-hjr265-me"

[params]
github = "hjr265"
goatCounterHost = "goatcounter.hjr265.me"
description = "Founder of Furqan Software. Built Toph, Bangladesh's leading competitive programming platform. Software engineer based in Dhaka 🇧🇩."
images = ["/avatar.png"]

[params.author]
name = "Mahmud Ridwan"
email = "m@hjr265.me"

[security.funcs]
getenv = ['^HUGO_', '^CI$', '^GITHUB_TOKEN$']

[markup.goldmark.parser.attribute]
block = true

[taxonomies]
tag = "tags"

[menu]
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 3

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 4

[[menu.main]]
name = "Notes"
url = "/notes/"
weight = 5

[[menu.main]]
name = "Timeline"
url = "/timeline/"
weight = 6


[markup.highlight]
lineNos = true

[markup.goldmark.renderer]
unsafe = true