baseURL = "https://hjr265.me/"
languageCode = "en-us"
title = "hjr265.me"
enableRobotsTXT = true
disqusShortname = "https-hjr265-me"

[params]
author = "Mahmud Ridwan"
github = "hjr265"

[taxonomies]
tag = "tags"

[menu]
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 3

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 5

[[menu.main]]
name = "Timeline"
url = "/timeline/"
weight = 6

[markup.highlight]
lineNos = true

[markup.goldmark.renderer]
unsafe = true

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "production"
url = "s3://hjr265.me?region=ap-south-1&endpoint=ap-south-1.linodeobjects.com&s3ForcePathStyle=true"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|woff|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
cacheControl = "max-age=0, no-cache, public"
gzip = true
